# Generated by Django 3.1.5 on 2021-01-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFlows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_flow_int', models.IntegerField(default=0)),
                ('sas_program', models.FileField(upload_to='')),
            ],
        ),
    ]
