# Generated by Django 3.1.5 on 2021-01-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('processconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processflows',
            options={'verbose_name': 'Process Flow', 'verbose_name_plural': 'Process Flows'},
        ),
        migrations.AddField(
            model_name='processflows',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processflows',
            name='project_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='processflows',
            name='sas_program_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
