# Generated by Django 3.1.5 on 2021-01-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processconfig', '0002_auto_20210116_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='SASPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sas_program', models.FileField(upload_to='')),
                ('order_number', models.IntegerField(default=0)),
                ('sas_program_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='processflows',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='processflows',
            name='sas_program_name',
        ),
        migrations.RemoveField(
            model_name='processflows',
            name='sas_program',
        ),
        migrations.AddField(
            model_name='processflows',
            name='sas_program',
            field=models.ManyToManyField(blank=True, null=True, to='processconfig.SASPrograms'),
        ),
    ]
