# Generated by Django 3.1.5 on 2021-01-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processconfig', '0003_auto_20210123_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processflows',
            name='sas_program',
            field=models.ManyToManyField(blank=True, to='processconfig.SASPrograms'),
        ),
    ]
