# Generated by Django 3.1.5 on 2021-01-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processconfig', '0005_auto_20210123_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processflows',
            name='process_flow_int',
        ),
        migrations.AddField(
            model_name='sasprograms',
            name='process_flow_int',
            field=models.IntegerField(default=0),
        ),
    ]
