# Generated by Django 3.1.5 on 2021-02-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processconfig', '0008_programflows_flow_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='processflows',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
